### ISSUE TITLE
Adding to a project

### ISSUE THREAD

**Issue by uyasarkocal** [andrew-levy/sweet-sfsymbols#1]
Hey, really promising project here. Congrats on the launch 🎉

I usually add https://github.com/birkir/react-native-sfsymbols to my projects, which works ok. But react native community needs this package right now, seems more flexible&reliable (On animations especially.) + the type support.

Want to use it on my new project, should I add this repo as a node package & then build or should I create a new module and clone ios folder to use it?

**Comment by andrew-levy** [comment]
Hey thanks! I haven't published it to NPM yet, but will this week! need to fix a few bugs first and clean up docs. Will be out sometime this week.

**Comment by andrew-levy** [comment]
@uyasarkocal just published to npm! let me know how it goes! https://www.npmjs.com/package/sweet-sfsymbols
