### ISSUE TITLE
Effects are not working

### ISSUE THREAD

**Issue by belle-chang** [andrew-levy/sweet-sfsymbols#3]
Hi, thanks for a great library! I'm currently trying to add effects to the SfSymbols, but I haven't been able to make it work. This is my code:
```
{/* Symbol Effect */}
          <SweetSFSymbol
            name="wifi.router"
            variableValue={varaibleValue}
            colors={["pink"]}
            symbolEffect={{
              type: "scale",
              direction: "up",
              repeat: true,
              value: varaibleValue,
            }}
          />
```

It's currently not animating at all with the button presses. Is there an issue with my set up? The example provided also does not animate in the same way as demonstrated in the Medium article: https://blorenzop.medium.com/how-to-animate-sf-symbols-in-swiftui-c3b504af4f44

**Comment by andrew-levy** [comment]
Hey, thanks! The `scale` animation type is an "indefinite" animation, and thus isn't compatible with variable values. Scale animations use the `isActive` property to signal that the scale needs to happen. If you want to use the variable value, you can try a different animation type like bounce:

```tsx
<SweetSFSymbol
  name="wifi.router"
  variableValue={varaibleValue}
  colors={['pink']}
  symbolEffect={{
    type: 'bounce',
    value: varaibleValue,
  }}
/>
```

Or do something like this to use the scale animation (Im not sure what your use case is here so you can change the isActive logic accordingly):
```tsx
<SweetSFSymbol
  name="wifi.router"
  variableValue={varaibleValue}
  colors={['pink']}
  symbolEffect={{
    type: 'scale',
    isActive: varaibleValue % 2 === 0,
  }}
/>
```

Please let me know if you have any other questions, I'm happy to help!

**Comment by andrew-levy** [comment]
It looks like there is a typescript issue with the second example, but it should work! @belle-chang. Ill work on updating the types in an upcoming release. Thanks again.

**Comment by belle-chang** [comment]
Thanks so much for the prompt replies!! I was able to get it to animate with your help and now it's working beautifully. Great library!!!

**Comment by andrew-levy** [comment]
awesome! glad you find it useful 😄 stay on the lookout for a minor version bump soon to fix some of those type issues
