### ISSUE TITLE
Eas build Fastlane failure [Expo SDK 50]

### ISSUE THREAD

**Issue by weizhe0412** [andrew-levy/sweet-sfsymbols#7]
[RUN_FASTLANE] 
❌  (node_modules/sweet-sfsymbols/ios/SweetSFSymbolsProps.swift:85:4)

  83 |   @Field var animateBy: String?
  84 |   @Field var inactiveLayers: String?
> 85 |   @Field var value: Any?
     |    ^ type 'Any' cannot conform to 'AnyArgument'
  86 |   @Field var isActive: Bool?
  87 |   
  88 |   @available(iOS 17.0, *)

[RUN_FASTLANE] › Compiling expo-location Pods/EXLocation » EXLocationTaskConsumer.m
[RUN_FASTLANE] › Compiling expo Pods/Expo » EXAppDefinesLoader.m
[RUN_FASTLANE] › Compiling expo Pods/Expo » Expo-dummy.m
[RUN_FASTLANE] ▸ ** BUILD FAILED **
[RUN_FASTLANE] ▸ The following build commands failed:
[RUN_FASTLANE] ▸        CompileSwift normal arm64 (in target 'SweetSFSymbols' from project 'Pods')
[RUN_FASTLANE] ▸        SwiftCompile normal arm64 Compiling\ SweetSFSymbolsExpoView.swift,\ SweetSFSymbolsModifiers.swift,\ SweetSFSymbolsModule.swift,\ SweetSFSymbolsProps.swift,\ SweetSFSymbolsView.swift /var/folders/xc/__ybnqtj24j5wwk7rdyvfqx00000gn/T/eas-build-local-nodejs/99d24f22-6532-47dc-9d8a-37b8b8c53112/build/node_modules/sweet-sfsymbols/ios/SweetSFSymbolsExpoView.swift /var/folders/xc/__ybnqtj24j5wwk7rdyvfqx00000gn/T/eas-build-local-nodejs/99d24f22-6532-47dc-9d8a-37b8b8c53112/build/node_modules/sweet-sfsymbols/ios/SweetSFSymbolsModifiers.swift /var/folders/xc/__ybnqtj24j5wwk7rdyvfqx00000gn/T/eas-build-local-nodejs/99d24f22-6532-47dc-9d8a-37b8b8c53112/build/node_modules/sweet-sfsymbols/ios/SweetSFSymbolsModule.swift /var/folders/xc/__ybnqtj24j5wwk7rdyvfqx00000gn/T/eas-build-local-nodejs/99d24f22-6532-47dc-9d8a-37b8b8c53112/build/node_modules/sweet-sfsymbols/ios/SweetSFSymbolsProps.swift /var/folders/xc/__ybnqtj24j5wwk7rdyvfqx00000gn/T/eas-build-local-nodejs/99d24f22-6532-47dc-9d8a-37b8b8c53112/build/node_modules/sweet-sfsymbols/ios/SweetSFSymbolsView.swift (in target 'SweetSFSymbols' from project 'Pods')
[RUN_FASTLANE] ▸ (2 failures)
[RUN_FASTLANE] ** BUILD FAILED **
[RUN_FASTLANE] 
[RUN_FASTLANE] 
[RUN_FASTLANE] The following build commands failed:
[RUN_FASTLANE]  CompileSwift normal arm64 (in target 'SweetSFSymbols' from project 'Pods')
[RUN_FASTLANE]  SwiftCompile normal arm64 Compiling\ SweetSFSymbolsExpoView.swift,\ SweetSFSymbolsModifiers.swift,\ SweetSFSymbolsModule.swift,\ SweetSFSymbolsProps.swift,\ SweetSFSymbolsView.swift /var/folders/xc/__ybnqtj24j5wwk7rdyvfqx00000gn/T/eas-build-local-nodejs/99d24f22-6532-47dc-9d8a-37b8b8c53112/build/node_modules/sweet-sfsymbols/ios/SweetSFSymbolsExpoView.swift /var/folders/xc/__ybnqtj24j5wwk7rdyvfqx00000gn/T/eas-build-local-nodejs/99d24f22-6532-47dc-9d8a-37b8b8c53112/build/node_modules/sweet-sfsymbols/ios/SweetSFSymbolsModifiers.swift /var/folders/xc/__ybnqtj24j5wwk7rdyvfqx00000gn/T/eas-build-local-nodejs/99d24f22-6532-47dc-9d8a-37b8b8c53112/build/node_modules/sweet-sfsymbols/ios/SweetSFSymbolsModule.swift /var/folders/xc/__ybnqtj24j5wwk7rdyvfqx00000gn/T/eas-build-local-nodejs/99d24f22-6532-47dc-9d8a-37b8b8c53112/build/node_modules/sweet-sfsymbols/ios/SweetSFSymbolsProps.swift /var/folders/xc/__ybnqtj24j5wwk7rdyvfqx00000gn/T/eas-build-local-nodejs/99d24f22-6532-47dc-9d8a-37b8b8c53112/build/node_modules/sweet-sfsymbols/ios/SweetSFSymbolsView.swift (in target 'SweetSFSymbols' from project 'Pods')
[RUN_FASTLANE] (2 failures)
[RUN_FASTLANE] Exit status: 65
[RUN_FASTLANE] 
[RUN_FASTLANE] +---------------------------------------+
[RUN_FASTLANE] |           Build environment           |
[RUN_FASTLANE] +-------------+-------------------------+
[RUN_FASTLANE] | xcode_path  | /Applications/Xcode.app |
[RUN_FASTLANE] | gym_version | 2.219.0                 |
[RUN_FASTLANE] | sdk         | iPhoneOS17.2.sdk        |
[RUN_FASTLANE] +-------------+-------------------------+
[RUN_FASTLANE] 
[RUN_FASTLANE] Looks like fastlane ran into a build/archive error with your project
[RUN_FASTLANE] It's hard to tell what's causing the error, so we wrote some guides on how
[RUN_FASTLANE] to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[RUN_FASTLANE] Before submitting an issue on GitHub, please follow the guide above and make
[RUN_FASTLANE] sure your project is set up correctly.
[RUN_FASTLANE] fastlane uses `xcodebuild` commands to generate your binary, you can see the
[RUN_FASTLANE] the full commands printed out in yellow in the above log.
[RUN_FASTLANE] Make sure to inspect the output above, as usually you'll find more error information there
[RUN_FASTLANE] 
[RUN_FASTLANE] [!] Error building the application - see the log above
[RUN_FASTLANE] Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.

Build failed
The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.
npx exited with non-zero code: 1
    Error: build command failed.

**Comment by andrew-levy** [comment]
can you please provide more details and a minimal example that i could reproduce? Are you using eas build or a local build? which version of xcode? @Quixot1k

**Comment by weizhe0412** [comment]
> can you please provide more details and a minimal example that i could reproduce? Are you using eas build or a local build? which version of xcode? @Quixot1k

1. npx create-expo-app@latest --template tabs@50 
2. npx expo install sweet-sfsymbols 
3. eas build --profile development --platform ios
4. FAILED

**Comment by andrew-levy** [comment]
Thanks @Quixot1k. I found the issue, supposedly the type `Any` isn't allowed for Record fields as of sdk 50. I'm going to test out my change a bit and push out a new version soon for you to retest.

**Comment by andrew-levy** [comment]
@Quixot1k just published `sweet-sfsymbols@0.5.0`. when you get a chance, can you try upgrading and try building again? If any other issues arise lmk.

**Comment by weizhe0412** [comment]
> @Quixot1k just published `sweet-sfsymbols@0.5.0`. when you get a chance, can you try upgrading and try building again? If any other issues arise lmk.

Solved 👏👏👏
